load('ext://helm_resource', 'helm_resource')
load('ext://namespace', 'namespace_create')
load('ext://secret', 'secret_from_dict')
load('../common/Tiltfile', 'helm_release')
update_settings(k8s_upsert_timeout_secs=120)

name_prefix = 'galoy-dev'
bitcoin_network = 'regtest'
bitcoind_rpcpassword = 'rpcpassword'
bitcoin_namespace = '{}-bitcoin'.format(name_prefix)
smoketest_namespace = '{}-smoketest'.format(name_prefix)

namespace_create(bitcoin_namespace)

k8s_yaml(secret_from_dict(
  name='bitcoind-rpcpassword',
  namespace=bitcoin_namespace,
  inputs={'password': bitcoind_rpcpassword},
))

helm_release(
  "../../charts/bitcoind",
  name="bitcoind",
  namespace=bitcoin_namespace,
  values=['./bitcoind-regtest-values.yml']
)

k8s_yaml(secret_from_dict(
  name='bitcoind-onchain-rpcpassword',
  namespace=bitcoin_namespace,
  inputs={'password': bitcoind_rpcpassword},
))

k8s_yaml(secret_from_dict(
  name='bitcoind-signer-descriptor',
  namespace=bitcoin_namespace,
  inputs={
    'descriptor_json_base64': local(
      "base64 bitcoind_signers_descriptors.json | tr -d '\n\r'"
    )
  },
))

helm_release(
  '../../charts/bitcoind',
  name='bitcoind-onchain',
  namespace=bitcoin_namespace,
  values=['./bitcoind-regtest-values.yml', './bitcoind-onchain-values.yml']
)

local_resource(
  name="bitcoind-block-generator",
  cmd='./generateBlock.sh',
  labels="bitcoin",
  resource_deps=["bitcoind-onchain", "bitcoind"]
)

helm_resource(
  name="lnd1",
  chart="../../charts/lnd",
  namespace=bitcoin_namespace,
  flags=[
    '--values=./lnd-regtest-values.yml',
  ],
  # resource_deps=["bitcoind-block-generator"],
)

helm_release(
  '../../charts/loop',
  name='loop1',
  namespace=bitcoin_namespace,
  values=['./loop-values.yml'],
)

k8s_resource(workload='loop1', resource_deps=['lnd1'])

# TODO: uncomment fulcrum when we actually use it
# helm_resource(
#   name="fulcrum",
#   chart="../../charts/fulcrum",
#   namespace=bitcoin_namespace,
#   flags=[
#     '--values=./fulcrum-regtest-values.yml',
#   ],
#   labels="bitcoin"
# )

# k8s_yaml(secret_from_dict(
#   name='fulcrum-smoketest',
#   namespace=bitcoin_namespace,
#   inputs={
#     'fulcrum_endpoint': 'fulcrum.{}.svc.cluster.local'.format(bitcoin_namespace),
#     'fulcrum_stats_port': 8080
#   },
# ))

k8s_yaml(secret_from_dict(
  name='bria-smoketest',
  namespace=bitcoin_namespace,
  inputs={
    'key': 'value'
  },
))

k8s_yaml(secret_from_dict(
  name='bria',
  namespace=bitcoin_namespace,
  inputs={
    'pg-con': 'postgres://bria:bria@bria-postgresql:5432/bria',
    'signer-encryption-key': local('openssl rand -hex 32'),
  },
))

helm_release(
  '../../charts/bria',
  name='bria',
  namespace=bitcoin_namespace,
  values=['./bria-values.yml'],
  dependency_build=True,
  add_repos=True
)

# TODO: uncomment mempool when we actually use it
helm_resource(
  name="mempool",
  chart="../../charts/mempool",
  namespace=bitcoin_namespace,
  flags=[
    '--values=./mempool-regtest-values.yml',
  ],
  labels="bitcoin"
)

k8s_yaml(secret_from_dict(
  name='mempool-smoketest',
  namespace=bitcoin_namespace,
  inputs={
    'mempool_endpoint': 'mempool.{}.svc.cluster.local'.format(bitcoin_namespace),
    'mempool_stats_port': 8999
  },
))

# TODO: uncomment rtl when we actually use it
# helm_resource(
#   name="rtl",
#   chart="../../charts/rtl",
#   namespace=bitcoin_namespace,
#   labels="bitcoin"
# )
#
# k8s_yaml(secret_from_dict(
#   name='rtl-smoketest',
#   namespace=bitcoin_namespace,
#   inputs={
#     'rtl_endpoint': 'rtl.{}.svc.cluster.local'.format(bitcoin_namespace),
#     'rtl_port': 3000
#   },
# ))

# create bitcoind smoketest secret from snippet above
k8s_yaml(secret_from_dict(
  name='bitcoind-smoketest',
  namespace=smoketest_namespace,
  inputs={
    'bitcoind_rpcpassword': bitcoind_rpcpassword,
    'bitcoind_endpoint': 'bitcoind.{}.svc.cluster.local'.format(bitcoin_namespace),
    'bitcoind_port': '18443',
    'bitcoind_user': 'rpcuser',
    'bitcoind_onchain_rpcpassword': bitcoind_rpcpassword,
    'bitcoind_onchain_endpoint': 'bitcoind.{}.svc.cluster.local'.format(bitcoin_namespace),
  }
))

# create lnd smoketest secret from snippet above
k8s_yaml(secret_from_dict(
  name='lnd-smoketest',
  namespace=smoketest_namespace,
  inputs={
    'lnd_api_endpoint': 'lnd1.{}.svc.cluster.local'.format(bitcoin_namespace),
    'lnd_p2p_endpoint': 'lnd1-p2p.{}.svc.cluster.local'.format(bitcoin_namespace),
  }
))

# create loop smoketest secret from snippet above
k8s_yaml(secret_from_dict(
  name='loop-smoketest',
  namespace=smoketest_namespace,
  inputs={
    'loop_api_endpoint': 'loop1.{}.svc.cluster.local'.format(bitcoin_namespace),
  }
))
