image:
  repository: us.gcr.io/galoy-org/galoy-admin-panel
  digest: "sha256:eab1a7fc68901792f2c73d0d7f7b4b675bd0a2f1866c07d6e0ffff56aca6432e" # METADATA:: repository=https://github.com/blinkbitcoin/blink;commit_ref=4d2a6c1;app=admin-panel;monorepo_subdir=apps/admin-panel;
  git_ref: "ef99dc0" # Not used by helm
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
adminPanel:
  adminCoreApi: http://admin-api.galoy-dev-galoy.svc.cluster.local:4001/admin/graphql
  nextAuthUrl: http://localhost:3000
  authorizedEmails: "satoshi@blink.sv,nakamoto@blink.sv"
  userRoleMap: {}
resources: {}
secrets:
  create: true
  googleOauthClientId: ""
  googleOauthClientSecret: ""
  nextAuthSecret: ""
otelExporterOtlpEndpoint: http://localhost:4318
tracingServiceName: "admin-panel"
