image:
  repository: us.gcr.io/galoy-org/galoy-admin-panel
  digest: "sha256:c9a5a8fe39852b44c5c4a8c51cf185dc3de3d1f314abb253823ee4f2fbef33af" # METADATA:: repository=https://github.com/GaloyMoney/galoy;commit_ref=e98fe29;app=admin-panel;monorepo_subdir=apps/admin-panel;
  git_ref: "ef99dc0" # Not used by helm
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
adminPanel:
  adminCoreApi: http://admin-api.galoy-dev-galoy.svc.cluster.local:4001/admin/graphql
  nextAuthUrl: http://localhost:3000
  authorizedEmails: "satoshi@galoy.io,nakamoto@blink.sv"
resources: {}
secrets:
  create: true
  googleOauthClientId: ""
  googleOauthClientSecret: ""
  nextAuthSecret: ""
otelExporterOtlpEndpoint: http://localhost:4318
tracingServiceName: "admin-panel"
