secrets:
  create: true
  mapApiKey: ""
map:
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "map"
image:
  repository: us.gcr.io/galoy-org/galoy-map
  digest: "sha256:3a8a8ecfd185cdcc19f76e9136dbfac3ea63b834c890803e1e4773f0e631fc3a" # METADATA:: repository=https://github.com/GaloyMoney/galoy;commit_ref=e98fe29;app=map;monorepo_subdir=apps/map;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
resources: {}
