load('ext://helm_resource', 'helm_resource')
load('ext://namespace', 'namespace_create')

name_prefix = 'galoy-dev'
galoy_namespace = '{}-galoy'.format(name_prefix)
addons_namespace = '{}-addons'.format(name_prefix)
bitcoin_namespace = '{}-bitcoin'.format(name_prefix)

namespace_create(addons_namespace)

k8s_yaml(secret_from_dict(
  name='admin-panel',
  namespace=addons_namespace,
  inputs={
    'next-auth-secret' : 'dummy123',
    'google-oauth-client-id' : 'dummy',
    'google-oauth-client-secret' : 'dummy',
    'github-oauth-client-id' : 'dummy',
    'github-oauth-client-secret' : 'dummy'
  }
))

k8s_yaml(helm(
  '../../charts/admin-panel',
  name='admin-panel',
  namespace=addons_namespace,
  values = ['./admin-panel-values.yml']
))

k8s_resource(workload='admin-panel', labels='addons')


k8s_yaml(helm(
  '../../charts/api-dashboard',
  name = 'dashboard',
  namespace = addons_namespace,
))
