secrets:
  create: true
  nextAuthSecret: ""
  clientSecret: ""
  escrowApiKey: ""
  pgCon: ""
voucher:
  hydraPublic: "http://galoy-hydra-public.galoy-dev-galoy.svc.cluster.local:4444"
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  voucherUrl: "http://localhost:3000"
  nextAuthUrl: ""
  clientId: ""
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "voucher"
  platformFeesInPpm: 2000
image:
  repository: us.gcr.io/galoy-org/galoy-voucher
  digest: "sha256:0c5543bb8fa07ee87ff4cbd608cbd11ac089b7911046b530bce340f6eb3c4e47" # METADATA:: repository=https://github.com/GaloyMoney/galoy;commit_ref=ccd31cc;app=voucher;monorepo_subdir=apps/voucher;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: voucher
    password: voucher
    database: voucher
resources: {}
