secrets:
  create: true
  nextAuthSecret: ""
  clientSecret: ""
  escrowApiKey: ""
  pgCon: ""
voucher:
  hydraPublic: "http://galoy-hydra-public.galoy-dev-galoy.svc.cluster.local:4444"
  coreUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  voucherUrl: "http://localhost:3000"
  nextAuthUrl: ""
  clientId: ""
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "voucher"
  platformFeesInPpm: 2000
image:
  repository: us.gcr.io/galoy-org/galoy-voucher
  digest: "sha256:0fe8a0c9ec80a09c44ee447d63f4101d13beb3ff503a2c023c033c5e36392742" # METADATA:: repository=https://github.com/GaloyMoney/galoy;commit_ref=2779c87;app=voucher;monorepo_subdir=apps/voucher;
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: voucher
    password: voucher
    database: voucher
resources: {}
