apiVersion: v2
name: blink-terminal
description: A Helm chart for the blink-terminal (BlinkPOS) merchant terminal
type: application
version: 0.1.0-dev
appVersion: 0.8.12
dependencies:
  - name: postgresql
    version: 18.5.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
