global:
  security:
    allowInsecureImages: true
secrets:
  create: true
  databaseUrl: ""
  redisPassword: ""
  jwtSecret: ""
  encryptionKey: ""
  networkEncryptionKey: ""
  blinkposApiKey: ""
  blinkposBtcWalletId: ""
  blinkWebhookSecret: ""
  citrusrateApiKey: ""
blinkTerminal:
  blinkApiUrl: "http://galoy-oathkeeper-proxy.galoy-dev-galoy.svc.cluster.local:4455/graphql"
  blinkEnvironment: "staging"
  redisHost: "localhost"
  redisPort: "6379"
  redisDb: "0"
  enableHybridStorage: "false"
  loglevel: "info"
  otelExporterOtlpEndpoint: http://localhost:4318
  tracingServiceName: "blink-terminal"
  citrusrateBaseUrl: "https://citrusrate-be.onrender.com"
image:
  repository: us.gcr.io/galoy-org/blink-terminal
  digest: "sha256:090e4e0362fd416e4342eaa1713bface66a791473495783f82e6becd52367a51" # METADATA:: repository=https://github.com/blinkbitcoin/blink-terminal;commit_ref=17212a0;app=blink-terminal;
psqlImage: "postgres:15"
ingress:
  enabled: false
service:
  port: 3000
  type: ClusterIP
postgresql:
  image:
    repository: bitnamilegacy/postgresql
  enabled: true
  auth:
    enablePostgresUser: false
    username: blink_terminal
    password: blink_terminal
    database: blink_terminal
resources: {}
