# TODO: Add labels for better grouping
def copy_secret(source_secret_name, source_namespace, target_namespace, resource_deps=[], target_secret_name=None):
  if target_secret_name == None:
    target_secret_name = source_secret_name

  delete_secret_cmd = 'kubectl -n {} delete secret {} --ignore-not-found=true'.format(target_namespace, target_secret_name)
  generate_secret_json_cmd = 'kubectl -n {} get secret {} -o json | jq "del(.metadata.namespace, .metadata.name) | .metadata.name = \\"{}\\""'.format(source_namespace, source_secret_name, target_secret_name)
  create_secret_cmd = 'kubectl -n {} apply -f -'.format(target_namespace)

  local_resource(
    name='{}-secret-copier'.format(target_secret_name),
    cmd='{} && {} | {}'.format(delete_secret_cmd, generate_secret_json_cmd, create_secret_cmd),
    resource_deps=resource_deps
  )
